namespace CataMedia.Desktop;

public static class UiStrings
{
    public static IReadOnlyDictionary<string, (string Pt, string En)> Values { get; } = new Dictionary<string, (string, string)>
    {
        ["MainMenu"] = ("Menu principal", "Main menu"),
        ["FileMenu"] = ("_Arquivo", "_File"),
        ["ViewMenu"] = ("_Exibir", "_View"),
        ["HelpMenu"] = ("A_juda", "_Help"),
        ["Exit"] = ("_Sair", "E_xit"),
        ["BrandSubtitle"] = ("Seus vídeos e áudios, no formato que você escolher.", "Your videos and audio, in the format you choose."),
        ["PrepareTitle"] = ("Preparar download", "Prepare download"),
        ["QueueHint"] = ("Acompanhe o andamento e selecione um item para ver o resultado.", "Follow progress and select an item to see its result."),
        ["EmptyQueue"] = ("Sua fila aparecerá aqui.\nCole os links ao lado e clique em Baixar para começar.", "Your queue will appear here.\nPaste links on the left and click Download to begin."),
        ["Help"] = ("Ajuda / Sobre", "Help / About"),
        ["Credits"] = ("Desenvolvimento: Wisley Vilela. Licença MIT.", "Developed by Wisley Vilela. MIT license."),
        ["Manual"] = ("Manual no GitHub", "Manual on GitHub"),
        ["LocalGuide"] = ("Guia local (sem internet)", "Local guide (offline)"),
        ["AppReleases"] = ("Abrir página de releases do CataMedia", "Open CataMedia releases page"),
        ["CheckAppUpdate"] = ("Verificar nova versão do CataMedia", "Check for a new CataMedia version"),
        ["CheckingAppUpdate"] = ("Consultando as releases oficiais do CataMedia… Você pode continuar usando o aplicativo.", "Checking official CataMedia releases… You can continue using the application."),
        ["AppCheckNotChecked"] = ("A consulta de novas versões ainda não foi concluída. Use o botão acima para verificar agora.", "The new version check has not completed yet. Use the button above to check now."),
        ["AppCheckUnavailable"] = ("Não foi possível consultar as novas versões. Verifique sua conexão e tente novamente mais tarde. Isso não impede o uso dos componentes já instalados.", "New versions could not be checked. Check your connection and try again later. This does not prevent using components already installed."),
        ["AppNoCompatibleRelease"] = ("Ainda não encontramos uma release estável do CataMedia C# 3.x com os pacotes Windows x64. As releases PowerShell 2.x são da geração anterior. Prévias podem ser consultadas na página de releases.", "No stable CataMedia C# 3.x release with Windows x64 packages was found. PowerShell 2.x releases belong to the previous generation. Preview releases can be viewed on the releases page."),
        ["AppNoNewerRelease"] = ("Não há uma versão estável compatível mais recente. A versão publicada identificada é {0}.", "No newer compatible stable version is available. The identified published version is {0}."),
        ["AppUpdateAvailable"] = ("Há uma nova versão do CataMedia: {0}. Abra a release para ler as novidades e escolher o instalador ou o ZIP portátil. A instalação é manual; seus componentes são atualizados separadamente.", "A new CataMedia version is available: {0}. Open the release to read what changed and choose the installer or portable ZIP. Installation is manual; your components are updated separately."),
        ["OpenAppRelease"] = ("Ver release do CataMedia", "View CataMedia release"),
        ["ReleaseHint"] = ("A consulta automática considera somente releases estáveis C# 3.x para Windows x64. Ela não instala nem baixa pacotes. Componentes como yt-dlp são atualizados pelo botão Componentes. Para experimentar uma prévia, consulte a página de releases.", "Automatic checking considers only stable C# 3.x releases for Windows x64. It does not install or download packages. Dependencies such as yt-dlp are updated through Components. To try a preview, visit the releases page."),
        ["Hint"] = ("Cole os links, escolha o formato e baixe. Um link por linha.", "Paste links, choose a format and download. One link per line."),
        ["Links"] = ("_Links", "_Links"), ["Paste"] = ("_Colar", "_Paste"),
        ["Language"] = ("_Idioma", "_Language"), ["Destination"] = ("_Salvar em", "_Save to"),
        ["ChooseFolder"] = ("Escolher pasta", "Choose folder"), ["MediaType"] = ("_Salvar como", "Save _as"),
        ["Video"] = ("Vídeo MP4", "MP4 video"), ["Audio"] = ("Só áudio", "Audio only"),
        ["Resolution"] = ("_Resolução máxima", "Maximum _resolution"),
        ["UpTo720"] = ("Até 720p", "Up to 720p"), ["UpTo1080"] = ("Até 1080p", "Up to 1080p"),
        ["ResolutionHint"] = ("A origem pode oferecer uma resolução menor; a resolução efetiva aparece ao concluir.", "The source may offer a lower resolution; the actual resolution is shown when complete."),
        ["AudioFormat"] = ("_Formato de áudio", "Audio _format"), ["AudioQuality"] = ("_Qualidade MP3", "MP3 _quality"),
        ["Low"] = ("Baixa — arquivo menor", "Low — smaller file"), ["Standard"] = ("Padrão — recomendada", "Standard — recommended"), ["High"] = ("Alta", "High"),
        ["ShortLow"] = ("Baixa", "Low"), ["ShortStandard"] = ("Padrão", "Standard"), ["ShortHigh"] = ("Alta", "High"),
        ["Lossless"] = ("WAV e FLAC preservam o áudio recebido, mas não recuperam qualidade perdida na origem.", "WAV and FLAC preserve the received audio but cannot restore quality lost at the source."),
        ["Advanced"] = ("Mais opções e componentes", "More options and components"),
        ["ComponentsHint"] = ("Selecione componentes existentes ou use o botão Componentes para obter e atualizar versões externas.", "Select existing components or use Components to obtain and update external versions."),
        ["Components"] = ("Componentes", "Components"),
        ["Component"] = ("_Componente", "_Component"),
        ["CheckNow"] = ("Verificar agora", "Check now"),
        ["InstallUpdate"] = ("Obter / atualizar", "Get / update"),
        ["RestorePrevious"] = ("Restaurar versão anterior", "Restore previous version"),
        ["Close"] = ("Fechar / cancelar operação", "Close / cancel operation"),
        ["Later"] = ("Mais tarde", "Later"),
        ["NotAvailable"] = ("não identificada", "not identified"),
        ["ComponentLocalVersionUnknown"] = ("Há um caminho selecionado, mas não foi possível identificar a versão do componente. Isso pode ocorrer com versões de desenvolvimento ou arquivos incompatíveis. O arquivo foi preservado; não é possível compará-lo com a versão disponível. Se optar por obter a versão oferecida, ela será validada e instalada separadamente.", "A path is selected, but the component version could not be identified. This can happen with development builds or incompatible files. The file was preserved; it cannot be compared with the available version. If you choose to obtain the offered version, it will be validated and installed separately."),
        ["Versions"] = ("Instalada: {0}\nDisponível: {1}", "Installed: {0}\nAvailable: {1}"),
        ["ComponentsConsent"] = ("O CataMedia usa três componentes: yt-dlp para baixar, FFmpeg e FFprobe para preparar e conferir os arquivos, e Node.js para acessar o YouTube. Você pode instalar todos nesta janela, um de cada vez. Cada download pede sua confirmação; os arquivos existentes são preservados.", "CataMedia uses three components: yt-dlp to download, FFmpeg and FFprobe to prepare and verify files, and Node.js to access YouTube. You can install all of them in this window, one at a time. Each download asks for confirmation; existing files are preserved."),
        ["CheckComponentsHint"] = ("Escolha um componente na lista. Sua versão será consultada automaticamente. Para repetir a consulta, use Verificar agora. Restaurar versão anterior se aplica às versões instaladas pelo CataMedia.", "Choose a component from the list. Its version will be checked automatically. Use Check now to repeat the check. Restore previous version applies to versions installed by CataMedia."),
        ["ConfirmComponent"] = ("Obter {0}, versão {1}, de {2}? O pacote será validado antes da ativação. A versão anterior gerenciada será preservada.", "Obtain {0}, version {1}, from {2}? The package will be validated before activation. The previous managed version will be preserved."),
        ["ConfirmRestore"] = ("Restaurar o componente anterior gerenciado? Preferências e mídia serão preservadas.", "Restore the previous managed component? Preferences and media will be preserved."),
        ["CheckingComponents"] = ("Verificando componentes…", "Checking components…"),
        ["DownloadingComponent"] = ("Obtendo componente… Fechar cancela a operação.", "Downloading component… Close cancels the operation."),
        ["ComponentTransferKnown"] = ("Recebidos {0:N1} MB de {1:N1} MB ({2:N0}%).", "Received {0:N1} MB of {1:N1} MB ({2:N0}%)."),
        ["ComponentTransferUnknown"] = ("Recebidos {0:N1} MB. O servidor não informou o tamanho total.", "Received {0:N1} MB. The server did not provide the total size."),
        ["ComponentTransferConnecting"] = ("Aguardando os primeiros dados do servidor há {0} s. Fechar esta janela cancela o download.", "Waiting for the first data from the server for {0} s. Close this window to cancel the download."),
        ["ComponentTransferWaiting"] = ("Últimos dados recebidos há {0} s. Se esse tempo aumentar, a transferência pode estar interrompida. Fechar esta janela cancela o download.", "Last data received {0} s ago. If this time increases, the transfer may be stalled. Close this window to cancel the download."),
        ["ValidatingComponent"] = ("Validando integridade e versão…", "Validating integrity and version…"),
        ["ComponentActivated"] = ("Componente validado e ativado.", "Component validated and activated."),
        ["ComponentReadyNext"] = ("{0}, versão {1}, está pronto para uso. Para instalar os demais componentes, escolha o próximo item na lista acima e aguarde a consulta. Você pode continuar nesta janela, sem reiniciar o CataMedia. Ao terminar, clique em Fechar.", "{0}, version {1}, is ready to use. To install the remaining components, choose the next item from the list above and wait for the check. You can continue in this window without restarting CataMedia. When finished, click Close."),
        ["ComponentCheckResultHint"] = ("Se Obter / atualizar estiver disponível, clique para instalar a versão apresentada. Se já está atualizada, escolha o próximo componente na lista. Você não precisa fechar o aplicativo entre instalações.", "If Get / update is available, click it to install the version shown. If it is already up to date, choose the next component from the list. You do not need to close the application between installations."),
        ["ComponentRestored"] = ("Versão anterior restaurada.", "Previous version restored."),
        ["ComponentCancelled"] = ("Operação cancelada ou tempo limite atingido. A versão ativa foi preservada.", "Operation cancelled or timed out. The active version was preserved."),
        ["ComponentFailed"] = ("Não foi possível concluir. A versão ativa foi preservada. Verifique rede, espaço disponível e permissões e tente novamente.", "Could not complete. The active version was preserved. Check network, available space and permissions and try again."),
        ["MissingComponents"] = ("Faltam componentes ou é preciso corrigir: {0}. Abra Obter / atualizar e instale cada item na mesma janela. Esses componentes são baixados separadamente do aplicativo. Se já os possui, selecione seus arquivos em Mais opções e componentes.", "Components are missing or need attention: {0}. Open Get / update and install each item in the same window. These components are downloaded separately from the application. If you already have them, select their files in More options and components."),
        ["UpdateNotice"] = ("yt-dlp instalado: {0}; disponível: {1}. Os sites mudam: versões antigas podem falhar. Atualizar é recomendado, mas não garante acesso a todo conteúdo.", "Installed yt-dlp: {0}; available: {1}. Sites change: older versions may fail. Updating is recommended but does not guarantee access to all content."),
        ["ChooseYtDlp"] = ("Escolher yt-dlp", "Choose yt-dlp"), ["FfmpegFolder"] = ("Pasta com FFmpeg e FFprobe", "Folder containing FFmpeg and FFprobe"),
        ["ChooseComponents"] = ("Escolher componentes", "Choose components"), ["ChooseNode"] = ("Escolher Node.js", "Choose Node.js"),
        ["Cookies"] = ("Cookies do navegador (opcional)", "Browser cookies (optional)"), ["NoCookies"] = ("Nenhum", "None"),
        ["CookiesHint"] = ("Só habilite para conteúdo que você tem autorização para acessar. O aplicativo não armazena seus cookies.", "Only enable for content you are authorized to access. The application does not store your cookies."),
        ["Save"] = ("Salvar preferências", "Save preferences"), ["Download"] = ("_Baixar", "_Download"),
        ["Cancel"] = ("_Cancelar", "_Cancel"), ["Retry"] = ("Repetir falhas", "Retry failed items"), ["OpenFolder"] = ("Abrir pasta", "Open folder"),
        ["Queue"] = ("Fila", "Queue"), ["QueueTitle"] = ("Título ou link", "Title or link"), ["QueueFormat"] = ("Formato", "Format"), ["QueueState"] = ("Estado", "Status"),
        ["Details"] = ("Detalhes do item selecionado", "Selected item details"),
        ["DetailsHint"] = ("Informações técnicas do motor podem estar em outro idioma. Nenhum log é salvo automaticamente.", "Technical engine details may be in another language. No logs are saved automatically."),
        ["Ready"] = ("Pronto para baixar.", "Ready to download."), ["PreferencesSaved"] = ("Preferências salvas.", "Preferences saved."),
        ["PreferencesUnreadable"] = ("As preferências não puderam ser lidas. O arquivo foi preservado e o salvamento está bloqueado.", "Preferences could not be read. The file was preserved and saving is disabled."),
        ["SaveFailed"] = ("Não foi possível salvar. Confira a permissão de gravação da pasta.", "Could not save. Check folder write permissions."),
        ["Inspecting"] = ("Consultando os links antes de baixar…", "Inspecting links before downloading…"),
        ["Preparing"] = ("Preparando…", "Preparing…"), ["Downloading"] = ("Baixando…", "Downloading…"),
        ["Processing"] = ("Preparando o arquivo final…", "Preparing the final file…"), ["Verifying"] = ("Verificando o arquivo…", "Verifying the file…"),
        ["Pending"] = ("Aguardando", "Waiting"), ["Running"] = ("Em andamento", "In progress"), ["Completed"] = ("Concluído", "Completed"),
        ["Failed"] = ("Falhou — consulte os detalhes", "Failed — see details"), ["Cancelled"] = ("Cancelado", "Cancelled"),
        ["Cancelling"] = ("Cancelando…", "Cancelling…"),
        ["CancelledHint"] = ("Cancelado. Arquivos parciais podem permanecer; os itens seguintes não foram baixados.", "Cancelled. Partial files may remain; subsequent items were not downloaded."),
        ["Summary"] = ("Concluídos: {0}. Falhas: {1}.", "Completed: {0}. Failed: {1}."),
        ["InputError"] = ("Confira os links, o destino e os componentes. Consulte os detalhes para identificar a causa.", "Check links, destination and components. See details to identify the cause."),
        ["NoLinks"] = ("Cole pelo menos um link válido, um por linha.", "Paste at least one valid link, one per line."),
        ["OpenFailed"] = ("Não foi possível abrir a pasta.", "Could not open the folder."),
        ["Portable"] = ("Modo portátil", "Portable mode"), ["Installed"] = ("Modo instalado", "Installed mode"),
        ["DataFolder"] = ("Dados: {0}", "Data: {0}"), ["ExecutableFilter"] = ("Executável (*.exe)|*.exe", "Executable (*.exe)|*.exe"),
        ["PlaylistTitle"] = ("Confirmar lista", "Confirm playlist"),
        ["PlaylistPrompt"] = ("{0}\nEsta lista contém {1} itens. O que deseja baixar?", "{0}\nThis playlist contains {1} items. What would you like to download?"),
        ["StartupError"] = ("Não foi possível abrir o CataMedia. Confira os marcadores de distribuição e a permissão de gravação. No portátil, extraia todo o ZIP em uma pasta gravável do usuário.", "Could not open CataMedia. Check distribution markers and write permission. For portable mode, extract the entire ZIP into a writable user folder."),
        ["WholePlaylist"] = ("Baixar a lista", "Download playlist"), ["SingleVideo"] = ("Só este vídeo", "Only this video"),
        ["SingleUnavailable"] = ("Este link aponta somente para uma lista; não há um vídeo individual selecionado.", "This link points only to a playlist; no individual video is selected."),
        ["PasteFailed"] = ("Não foi possível ler a área de transferência. Cole os links manualmente.", "Could not read the clipboard. Paste the links manually.")
    };

    public static string Get(string key, string language) => language == "en" ? Values[key].En : Values[key].Pt;
}
